---
title: "Predicting Newborn Weight"
author: Liam Coleman-Aulenbach, Venessa Keung, Lucy Wang
output: pdf_document
documentclass: article
---

```{r setup, include=FALSE}
# Knitr Configuration
knitr::opts_chunk$set(include=FALSE, results="hide")
```

```{r import}
# Import
births <- read.csv("chds_births.csv")
```

# Summary

# Model Selection

## Data Diagnostic

### Data Exploration

### Outliers

### Missing Data

## Data Preprocessing

### Filling Missing Values

```{r mice}
library(mice)
m <- 5

multiplyImputedBirths <- mice(births, m = m, method = "pmm", seed = 500, printFlag = FALSE)

imputedBirths <- lapply(1:m, function(i) complete(multiplyImputedBirths, i))
```


### Decoding

```{r preprocessData}
# Re-encoding and labelling variates
decodeBirthVariates <- function (birthsDataset) {
  newDataset = data.frame(birthsDataset)
  
  ethLabels <- c(
    "Caucasian",
    "Mexican",
    "African-American",
    "Asian",
    "Mixed",
    "Other"
  )
  edLabels <- c(
    "Elementary School",
    "Middle School",
    "High School",
    "High School + Trade School",
    "High School + Some College",
    "College Graduate",
    "Trade School",
    "High School Unclear"
  )

  newDataset$meth <- cut(
    birthsDataset$meth,
    breaks = c(0, 5:10), 
    labels = ethLabels,
    right = TRUE,
    include.lowest= TRUE
  )
  
  newDataset$med <- cut(
    birthsDataset$med,
    breaks = 0:8, 
    labels = edLabels,
    right = FALSE
  )
  
  newDataset$feth <- cut(
    birthsDataset$feth,
    breaks = c(0, 5:10), 
    labels = ethLabels,
    right = TRUE,
    include.lowest= TRUE
  )
  
  newDataset$fed <- cut(
    birthsDataset$fed,
    breaks = 0:8, 
    labels = edLabels,
    right = FALSE
  )
  
  newDataset$smoke <- cut(
    birthsDataset$smoke,
    breaks = 0:4, 
    labels = c(
      "Never",
      "Smokes Now",
      "Until Pregnancy",
      "Doesn't Smoke Anymore"
    ),
    right = FALSE
  )
  
  newDataset$marital <- cut(
    birthsDataset$marital,
    breaks = 0:5, 
    labels = c(
      "Married",
      "Legally Separated",
      "Divorced",
      "Widowed",
      "Never Married"
    )
  )
  
  newDataset$number <- cut(
    birthsDataset$number,
    breaks = 0:10,
    labels = c(
      "Never Smoked",
      "1-4",
      "5-9",
      "10-14",
      "15-19",
      "20-29",
      "30-39",
      "40-60",
      "More Than 60",
      "Smoked But Don't Know How Much"
    ),
    right = FALSE
  )

  newDataset$time <- cut(
    birthsDataset$time,
    breaks = 0:10,
    labels = c(
      "Never Smoked",
      "Still Smokes",
      "During Pregnancy",
      "Less Than A Year",
      "1-2 Years",
      "2-3 Years",
      "3-4 Years",
      "5-9 Years",
      "More Than 10 Years",
      "Quit But Don't Know When"
    ),
    right = FALSE
  )

  newDataset$income <- cut(
    birthsDataset$income,
    breaks = c(0, 1, 2, 10),
    labels = c(
      "Under 2500",
      "2500-4999",
      "5000-Over 25000"
    ),
    right = FALSE
  )
  
  newDataset
}

decodedImputedBirths <- lapply(imputedBirths, decodeBirthVariates)
```

## Candidate Model 1

### Automated Model Selection

```{r model1}
birthModelAIC <- 10000000
finalAutomatedBirthModel <- lm(wt ~ 1, data = births)

for(birthModel in decodedImputedBirths) {
  adjustedBirthModel <- birthModel
  adjustedBirthModel$smoke <- NULL
  adjustedBirthModel$number <- NULL
  M0 <- lm(wt ~ 1, data = birthModel)
  Mmax <- lm(wt ~ (.- marital - time - meth - feth - med - fed)^2 + marital + time + meth + feth + med + fed, data = adjustedBirthModel)
    
  #checking if there are betas that are NA
  beta.max <- coef(Mmax)
  names(beta.max)[is.na(beta.max)]
  anyNA(coef(Mmax))

  buildModel <- function(adjustedBirthModel, predictVar, direction="both", excludeVars=c(), MAX_ITERS=1000) {
    data = na.omit(adjustedBirthModel[, !colnames(adjustedBirthModel) %in% excludeVars])
    step(
      lm(
        as.formula(paste(predictVar, "~", ".")),
        data=data
      ),
      scope = list(lower = M0, upper = Mmax),
      direction=direction,
      steps=MAX_ITERS
    )
  }
  model <- buildModel(adjustedBirthModel, "wt", excludeVars=c())
  modelAIC <- AIC(model)
  if (modelAIC < birthModelAIC) {
    finalAutomatedBirthModel <- model
    birthModelAIC <- modelAIC
  }
}

```


## Candidate Model 2

### Hand-crafted Features
```{r craftFeatures}
poundsToKg <- 0.453592
inchesToM <- 0.0254
underweightNormalBoundary <- 18.5
normalOverweightBoundary <- 25
overweightObeseBoundary <- 30
#obeseWeightGain <- mean(c(11, 20))
#overweightWeightGain <- mean(c(15, 25))
#normalWeightGain <- mean(c(25, 30))
#underweightWeightGain <- mean(c(28, 40))
isUnderweight <- function (x) x < underweightNormalBoundary
isNormal <- function (x) x < normalOverweightBoundary & x >= underweightNormalBoundary
isOverweight <- function (x) x < overweightObeseBoundary & x >= normalOverweightBoundary
isObese <- function (x) x >= overweightObeseBoundary

bmi <- function (wtLbs, htIn) (wtLbs * poundsToKg) / (htIn * inchesToM)^2
#obesePrePregnancyBMI <- function (pregnancyWt, ht) bmi(pregnancyWt - obeseWeightGain, ht)
#overweightPrePregnancyBMI <- function (pregnancyWt, ht) bmi(pregnancyWt - overweightWeightGain, ht)
#normalPrePregnancyBMI <- function (pregnancyWt, ht) bmi(pregnancyWt - normalWeightGain, ht)
#underweightPrePregnancyBMI <- function (pregnancyWt, ht) bmi(pregnancyWt - underweightWeightGain, ht)

prePregnancyBMI <- function (pregnancyWt, ht) {
  attemptOrder = sample(
    list(
      c(obesePrePregnancyBMI, isObese),
      c(overweightPrePregnancyBMI, isOverweight),
      c(normalPrePregnancyBMI, isNormal),
      c(underweightPrePregnancyBMI, isUnderweight)
    ),
    4
  )
  
  for (bmiCategoryPair in attemptOrder) {
    if (bmiCategoryPair[[2]](bmiCategoryPair[[1]](pregnancyWt, ht))) {
      return(bmiCategoryPair[[1]](pregnancyWt, ht))
    }
  }
}

weightFromBMI <- function (prePregnancyBMI, ht) {
  (1 / poundsToKg) * prePregnancyBMI * (ht * inchesToM)^2
}

smokingImpact <- function (time, number) {
  # There are no 9s in number, so we do not need to handle this case
  # Let's just call 8 a 1
  # 
  number[number == 8] <- 1
  cigaretteEffectRatio = 6
  # Take the average of the bounds of the range of cigarettes smoked by a given category
  # as the approximate exact number of cigarettes smoked per day
  numCigs = (number <= 4) * (5 * number - 2.5) + (number > 4) * (10 * number - 25.5)
  # https://www.med.uottawa.ca/sim/data/Smoking_and_Health_e.htm shows that it took a
  # six-fold increase in the number of cigarettes smoked a day to double the impact
  # on the likelihood of developing lung cancer. We approximate the effect of smoking
  # on birth with this ratio too.
  activeSmokingImpact = (number != 0) * 2^(number / cigaretteEffectRatio)
  
  impactTimeDecay = 2
  
  # Approximate a scalar number of years since quiting based on the categorical variable
  yearsQuit = (time >= 3) * (-2.5 + time) + (time >= 7) * (-18.5 + 3 * time)
  # Time = 1 or 2 are special cases with 0 decay
  yearsQuit = yearsQuit * (time >= 3)
  
  decayedSmokingImpact = activeSmokingImpact * exp(-yearsQuit / impactTimeDecay)
  
  decayedSmokingImpact
}

craftFeatures <- function (imputedBirthsDataset) {
  newDataset = decodeBirthVariates(imputedBirthsDataset)

  newDataset$sameEth <- factor(
    imputedBirthsDataset$meth == imputedBirthsDataset$feth,
    labels = c("Different", "Same")
  )
  # What about "Other" though?
  
  newDataset$htDiff <- newDataset$fht - newDataset$mht
    
  newDataset$lateMom <- factor(
    newDataset$parity == 0 & newDataset$mage >= 35,
    labels = c("Not late", "Late")
  )

  newDataset$mBMI <- bmi(newDataset$mwt, newDataset$mht)
  
  #newDataset$mwt <- weightFromBMI(newDataset$mBMI, newDataset$mht)
  
  newDataset$mBMICategory <- factor(
    1 * isNormal(newDataset$mBMI)
      + 2 * isOverweight(newDataset$mBMI)
      + 3 * isObese(newDataset$mBMI),
    labels = c("Underweight", "Normal", "Overweight", "Obese")
  )
  
  newDataset$smokingImpact <- smokingImpact(
    imputedBirthsDataset$time,
    imputedBirthsDataset$number
  )
  newDataset$smokingQuitCategory <- factor(
    1 * (imputedBirthsDataset$time == 2) + 2 * (imputedBirthsDataset$time == 1),
    labels = c("Before/Never", "During", "Continued")
  )
  
  newDataset
}
```


### Automated Model Selection



# Model Diagnostics

## Significance


## AIC


## Cross-Validation


# Discussion



# Appendix
```{r, ref.label=knitr::all_labels(), echo=TRUE, eval=FALSE, include=TRUE}
```
